name: Build and Deploy Resumes

on:
  push:
    branches: [ main ] # Or your default branch name
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [en, nl] # Build for both English and Dutch

    steps:
    - uses: actions/checkout@v3

    - name: Setup Pandoc
      uses: r-lib/actions/setup-pandoc@v2
      with:
        pandoc-version: 'latest'

    - name: Install wkhtmltopdf
      run: |
        sudo apt-get update
        sudo apt-get install -y wkhtmltopdf

    - name: Convert to PDF
      run: |
        if [ "${{ matrix.language }}" == "en" ]; then
          pandoc resume-en.md -o resume-en.pdf --pdf-engine=wkhtmltopdf
        else
          pandoc resume.md -o resume.pdf --pdf-engine=wkhtmltopdf
        fi

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v3
      with:
        name: resume-pdf-${{ matrix.language }}
        path: resume-${{ matrix.language }}.pdf

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: matrix.language == 'en' # Deploy only English markdown to main Pages
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: . # Publish the root directory for English Markdown

  deploy-pdf:
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [en, nl]

    steps:
      - name: Download PDF artifact
        uses: actions/download-artifact@v3
        with:
          name: resume-pdf-${{ matrix.language }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: pdf-${{ matrix.language }} # Publish to language-specific subdirectories
          publish_branch: pdf-${{ matrix.language }} # Separate branch for each PDF